on:
  push:
    branches: [ "aws-lambda-add-role-param" ]
  workflow_dispatch:
    inputs:
      component:
        description: 'Version component to increment'
        required: true
        default: 'patch'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Version Number
      uses: fwilhe2/bump-version@main
      id: bump
      with:
        component: ${{ github.event.inputs.component }}
