on:
  push:
    branches: [ "aws-lambda-add-role-param" ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        project_path: "./sampo/sanpo"
        binary_name: "main"
        extra_files: LICENSE README.md