# .github/workflows/release.yml:
name: Release

on:
  push:
    branches:
      - aws-lambda-add-role-param

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit-message: 'CI: bumps version to {{version}} [skip ci]'